name: sso
description: A simple abstract single sign-on library for Dart
version: 0.0.3
author: Long Do <me@dotronglong.com>
homepage: https://github.com/dotronglong/dart-sso

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter